[project]
name = "PowerChat"
structure = 1
version = "1.0.0"
main = "src/main.cbl"
copyright = ""
license_model = "MIT"
destination_folder = "PowerChat"
debug_compilation = true

[files]
sources = ["src/main.cbl"]
forms = [
    "forms/chat-form.cfrm",
    "forms/topics-form.cfrm",
    "forms/documents-form.cfrm",
    "forms/settings-form.cfrm",
    "forms/files-form.cfrm",
    "forms/prompts-form.cfrm",
    "forms/kb-folder-form.cfrm",
    "forms/providers-form.cfrm",
    "forms/model-form.cfrm",
    "forms/agents-form.cfrm",
]
assets = [
    "assets/flags/en.png",
    "assets/flags/pt.png",
    "assets/flags/es.png",
    "assets/flags/fr.png",
    "assets/flags/jp.png",
    "assets/flags/cn.png",
    "assets/robot.svg",
    "assets/Titan_Voyages_Logo_270x80.png",
    "assets/Titan_Voyages_Logo_45x45.png",
]
documentation = []
generated = [
    "generated/chat-form.cbl",
    "generated/topics-form.cbl",
    "generated/documents-form.cbl",
    "generated/settings-form.cbl",
    "generated/files-form.cbl",
    "generated/prompts-form.cbl",
    "generated/kb-folder-form.cbl",
    "generated/providers-form.cbl",
    "generated/model-form.cbl",
    "generated/agents-form.cbl",
]
indexed = []

[runtime]
fixed_format = false

[forms]
main-form = "CHAT-FORM"
main-form-seal = "a41d3d967fa10fcfaf1747d5d829dee29f81a640748913f5aa696fc8ca719d62"
