[project]
name = "PowerChat"
structure = 1
version = "1.0.0"
main = "src/main.cbl"
copyright = ""
license_model = "MIT"
destination_folder = "PowerChat"
debug_compilation = true

[files]
sources = ["src/main.cbl"]
forms = [
    "forms/chat-form.cfrm",
    "forms/topics-form.cfrm",
    "forms/documents-form.cfrm",
    "forms/settings-form.cfrm",
    "forms/files-form.cfrm",
    "forms/prompts-form.cfrm",
]
assets = [
    "assets/flags/en.png",
    "assets/flags/pt.png",
    "assets/flags/es.png",
    "assets/flags/fr.png",
    "assets/flags/jp.png",
    "assets/flags/cn.png",
    "assets/robot.svg",
]
documentation = []
generated = [
    "generated/chat-form.cbl",
    "generated/topics-form.cbl",
    "generated/documents-form.cbl",
    "generated/settings-form.cbl",
    "generated/files-form.cbl",
    "generated/prompts-form.cbl",
]
indexed = []

[runtime]
fixed_format = false

[forms]
main-form = "CHAT-FORM"
main-form-seal = "cb378d82aa968efb6771a17adf2576b48f14bef6cac1a8b2d4bb1d012b13cb12"
