[project]
name = "Label Test"
version = "1.0.0"
main = "generated/label.cbl"
copyright = ""
license_model = ""
license_text = ""

[files]
sources = []
forms = ["forms/label.cfrm"]
assets = []
documentation = []
generated = ["generated/label.cbl"]
indexed = []

[runtime]
fixed_format = false

[ide]
theme = ""
background_image = ""
background_opacity = 70
