// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Emerson Lopes and PowerRustCOBOL contributors
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

//! Localised quote pool for the welcome pane. Each language has its own set so
//! the rotating quote follows the IDE's selected language. Every language
//! carries the FULL pool, in the same order as English, so no quote is ever
//! missing from one language or shown in another (scripture references are
//! localised, e.g. `Proverbs` → `Proverbios`).

use crate::i18n::Language;

/// `(author, quote)` pairs.
type Quote = (&'static str, &'static str);

/// The quote pool for `lang`.
pub fn quotes(lang: Language) -> &'static [Quote] {
    match lang {
        Language::Spanish => ES,
        Language::Portuguese => PT,
        Language::Japanese => JA,
        Language::Chinese => ZH,
        Language::English => EN,
        Language::French => FR,
    }
}

const EN: &[Quote] = &[
    ("Alan Kay", "The best way to predict the future is to invent it."),
    ("Bill Gates", "We’re changing the world with technology."),
    ("Steve Jobs", "Technology alone is not enough."),
    ("Steve Jobs", "The best way to create value in the 21st century is to connect Creativity with Technology."),
    ("Steve Jobs", "Everybody in this country should learn how to program a computer, because it teaches you how to think."),
    ("Steve Jobs", "Innovation is the only way to win."),
    ("Steve Jobs", "Every once in a while a revolutionary product comes along that changes everything."),
    ("Linus Torvalds", "Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program."),
    ("Bill Gates", "We are not even close to finishing the basic dream of what the PC can be."),
    ("Mark Zuckerberg", "Move fast and break things. Unless you are breaking stuff, you are not moving fast enough."),
    ("Elon Musk", "Any product that needs a manual to work is broken."),
    ("Alan Kay", "Technology is anything invented after you were born."),
    ("Grace Hopper", "A ship in port is safe, but that’s not what ships are built for. Sail out to sea and do new things."),
    ("Grace Hopper", "It’s easier to ask forgiveness than it is to get permission."),
    ("Alan Kay", "Simple things should be simple; complex things should be possible."),
    ("Steve Jobs", "Design is not just what it looks like and feels like. Design is how it works."),
    ("Bill Gates", "Your most unhappy customers are your greatest source of learning."),
    ("Elon Musk", "When something is important enough, you do it even if the odds are not in your favor."),
    ("Alan Kay", "People who are really serious about software should make their own hardware."),
    ("Edsger Dijkstra", "Computer science is no more about computers than astronomy is about telescopes."),
    ("Grace Hopper", "Humans are allergic to change. They love to say, ‘We’ve always done it this way.’"),
    ("Jean Sammet", "I do not consider an assembly language (even a sophisticated one) to be a programming language."),
    ("Sister Mary Kenneth Keller", "We’re having an information explosion, and it’s certainly obvious that information is of no use unless it’s available."),
    ("Tim Berners-Lee", "The Web is more a social creation than a technical one."),
    ("Vint Cerf", "The internet is a reflection of our society and that mirror is going to be reflecting what we see."),
    ("Jeff Bezos", "What we need to do is always lean into the future."),
    ("Satya Nadella", "The true opportunity is to build products that people love and that solve real problems."),
    ("Donald Knuth", "The most important property of a program is whether it accomplishes the intention of its user."),
    ("Linus Torvalds", "If you think your users are idiots, only idiots will use it."),
    ("Elon Musk", "Failure is an option here. If things are not failing, you are not innovating enough."),
    ("Proverbs 1:7", "The fear of the Lord is the beginning of knowledge, but fools despise wisdom and instruction."),
    ("Proverbs 3:5-6", "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight."),
    ("Proverbs 2:6", "For the Lord gives wisdom; from his mouth come knowledge and understanding."),
    ("Proverbs 4:7", "The beginning of wisdom is this: Get wisdom. Though it cost all you have, get understanding."),
    ("Proverbs 16:16", "How much better to get wisdom than gold, to get insight rather than silver!"),
    ("Proverbs 20:18", "Plans are established by seeking advice; so if you wage war, obtain guidance."),
    ("Proverbs 21:5", "The plans of the diligent lead to profit as surely as haste leads to poverty."),
    ("Proverbs 16:3", "Commit to the Lord whatever you do, and he will establish your plans."),
    ("Proverbs 12:14", "Wise words bring many benefits, and hard work brings rewards."),
    ("Proverbs 10:14", "The wise store up knowledge, but the mouth of a fool invites ruin."),
    ("Proverbs 16:18", "Pride goes before destruction, a haughty spirit before a fall."),
    ("Proverbs 15:1", "A gentle answer turns away wrath, but a harsh word stirs up anger."),
    ("Proverbs 27:17", "As iron sharpens iron, so one person sharpens another."),
    ("Proverbs 4:23", "Above all else, guard your heart, for everything you do flows from it."),
    ("Proverbs 18:21", "The tongue has the power of life and death, and those who love it will eat its fruit."),
    ("Proverbs 15:14", "A wise person is hungry for knowledge, while the fool feeds on foolishness."),
    ("Proverbs 13:4", "Lazy people want much but get little, but those who work hard will prosper."),
    ("Proverbs 9:10", "The fear of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding."),
    ("Proverbs 3:15", "She is more precious than rubies; nothing you desire can compare with her."),
    ("Proverbs 3:13", "Blessed are those who find wisdom, those who gain understanding."),
    ("Proverbs 3:17", "Her ways are pleasant ways, and all her paths are peace."),
    ("Proverbs 3:18", "She is a tree of life to those who take hold of her; those who hold her fast will be blessed."),
    ("Proverbs 4:5", "Get wisdom, get understanding; do not forget my words or turn away from them."),
    ("Proverbs 4:18", "The path of the righteous is like the morning sun, shining ever brighter till the full light of day."),
    ("Proverbs 23:12", "Apply your heart to instruction and your ears to words of knowledge."),
    ("Proverbs 3:27", "Do not withhold good from those to whom it is due, when it is in your power to act."),
    ("Proverbs 17:22", "A cheerful heart is good medicine, but a crushed spirit dries up the bones."),
    ("Proverbs 15:13", "A happy heart makes the face cheerful, but heartache crushes the spirit."),
    ("Proverbs 16:24", "Pleasant words are a honeycomb, sweet to the soul and healing to the bones."),
    ("Proverbs 11:8", "The righteous person is rescued from trouble, and it falls on the wicked instead."),
    ("Proverbs 29:11", "A fool gives full vent to his anger, but a wise man keeps himself under control."),
    ("Mark 9:23", "Jesus said to him, ‘If you can believe, all things are possible to him who believes.’"),
    ("John 14:6", "Jesus answered, “I am the way and the truth and the life. No one comes to the Father except through Me.”"),
];

const ES: &[Quote] = &[
    ("Alan Kay", "La mejor manera de predecir el futuro es inventarlo."),
    ("Bill Gates", "Estamos cambiando el mundo con la tecnología."),
    ("Steve Jobs", "La tecnología por sí sola no es suficiente."),
    ("Steve Jobs", "La mejor manera de crear valor en el siglo XXI es unir la creatividad con la tecnología."),
    ("Steve Jobs", "Todo el mundo en este país debería aprender a programar un ordenador, porque te enseña a pensar."),
    ("Steve Jobs", "La innovación es la única forma de ganar."),
    ("Steve Jobs", "De vez en cuando aparece un producto revolucionario que lo cambia todo."),
    ("Linus Torvalds", "La mayoría de los buenos programadores no programan porque esperen que les paguen o que el público los admire, sino porque programar es divertido."),
    ("Bill Gates", "Ni siquiera estamos cerca de cumplir el sueño básico de lo que puede ser el PC."),
    ("Mark Zuckerberg", "Muévete rápido y rompe cosas. Si no estás rompiendo nada, no te estás moviendo lo bastante rápido."),
    ("Elon Musk", "Cualquier producto que necesite un manual para funcionar está roto."),
    ("Alan Kay", "La tecnología es todo lo que se inventó después de que nacieras."),
    ("Grace Hopper", "Un barco en el puerto está seguro, pero los barcos no se construyen para eso. Sal al mar y haz cosas nuevas."),
    ("Grace Hopper", "Es más fácil pedir perdón que pedir permiso."),
    ("Alan Kay", "Las cosas simples deben ser simples; las complejas, posibles."),
    ("Steve Jobs", "El diseño no es solo cómo se ve y se siente. El diseño es cómo funciona."),
    ("Bill Gates", "Tus clientes más insatisfechos son tu mayor fuente de aprendizaje."),
    ("Elon Musk", "Cuando algo es lo bastante importante, lo haces aunque las probabilidades no estén a tu favor."),
    ("Alan Kay", "Quien se toma el software realmente en serio debería fabricar su propio hardware."),
    ("Edsger Dijkstra", "La informática no trata de computadoras más de lo que la astronomía trata de telescopios."),
    ("Grace Hopper", "Los humanos son alérgicos al cambio. Les encanta decir: «Siempre lo hemos hecho así»."),
    ("Jean Sammet", "No considero que un lenguaje ensamblador (ni siquiera uno sofisticado) sea un lenguaje de programación."),
    ("Sister Mary Kenneth Keller", "Vivimos una explosión de información, y es evidente que la información no sirve de nada si no está disponible."),
    ("Tim Berners-Lee", "La Web es más una creación social que técnica."),
    ("Vint Cerf", "Internet es un reflejo de nuestra sociedad, y ese espejo va a reflejar lo que vemos."),
    ("Jeff Bezos", "Lo que debemos hacer es inclinarnos siempre hacia el futuro."),
    ("Satya Nadella", "La verdadera oportunidad es crear productos que la gente ame y que resuelvan problemas reales."),
    ("Donald Knuth", "La propiedad más importante de un programa es si cumple la intención de su usuario."),
    ("Linus Torvalds", "Si crees que tus usuarios son idiotas, solo los idiotas lo usarán."),
    ("Elon Musk", "Aquí fallar es una opción. Si las cosas no fallan, no estás innovando lo suficiente."),
    ("Proverbios 1:7", "El temor del Señor es el principio del conocimiento; los necios desprecian la sabiduría y la instrucción."),
    ("Proverbios 3:5-6", "Confía en el Señor de todo corazón y no en tu propia inteligencia; reconócelo en todos tus caminos, y él enderezará tus sendas."),
    ("Proverbios 2:6", "Porque el Señor da la sabiduría; de su boca vienen el conocimiento y la inteligencia."),
    ("Proverbios 4:7", "La sabiduría es lo principal; adquiere sabiduría, y sobre todas tus posesiones adquiere inteligencia."),
    ("Proverbios 16:16", "¡Cuánto mejor es adquirir sabiduría que oro, y adquirir inteligencia que plata!"),
    ("Proverbios 20:18", "Los planes se afirman con el consejo; haz la guerra con buena dirección."),
    ("Proverbios 21:5", "Los planes del diligente llevan a la abundancia, como la prisa lleva a la pobreza."),
    ("Proverbios 16:3", "Encomienda al Señor tus obras, y tus planes se cumplirán."),
    ("Proverbios 12:14", "Las palabras sabias traen muchos beneficios, y el trabajo duro trae su recompensa."),
    ("Proverbios 10:14", "Los sabios guardan el conocimiento, pero la boca del necio atrae la ruina."),
    ("Proverbios 16:18", "Antes del quebrantamiento está la soberbia, y antes de la caída, la altivez de espíritu."),
    ("Proverbios 15:1", "La respuesta amable calma el enojo, pero la palabra hiriente lo enciende."),
    ("Proverbios 27:17", "El hierro se afila con el hierro, y el hombre con su prójimo."),
    ("Proverbios 4:23", "Sobre todas las cosas, guarda tu corazón, porque de él mana la vida."),
    ("Proverbios 18:21", "La lengua tiene poder sobre la vida y la muerte; quien la ama comerá de su fruto."),
    ("Proverbios 15:14", "El sabio tiene hambre de conocimiento, mientras que el necio se alimenta de necedad."),
    ("Proverbios 13:4", "El perezoso desea y nada alcanza, pero el diligente prospera."),
    ("Proverbios 9:10", "El temor del Señor es el principio de la sabiduría, y conocer al Santo es inteligencia."),
    ("Proverbios 3:15", "Es más preciosa que las perlas; nada de lo que deseas se le puede comparar."),
    ("Proverbios 3:13", "Dichoso el que halla la sabiduría, el que adquiere inteligencia."),
    ("Proverbios 3:17", "Sus caminos son caminos deleitosos, y todas sus sendas son paz."),
    ("Proverbios 3:18", "Es árbol de vida para quienes la abrazan; dichosos los que la retienen."),
    ("Proverbios 4:5", "Adquiere sabiduría, adquiere inteligencia; no olvides mis palabras ni te apartes de ellas."),
    ("Proverbios 4:18", "La senda de los justos es como la luz de la aurora, que brilla cada vez más hasta que el día es perfecto."),
    ("Proverbios 23:12", "Aplica tu corazón a la enseñanza y tus oídos a las palabras del conocimiento."),
    ("Proverbios 3:27", "No niegues el bien a quien se le debe, cuando esté en tu mano hacerlo."),
    ("Proverbios 17:22", "El corazón alegre es buena medicina, pero el espíritu abatido seca los huesos."),
    ("Proverbios 15:13", "El corazón alegre hermosea el rostro, pero el dolor del corazón abate el espíritu."),
    ("Proverbios 16:24", "Las palabras amables son un panal de miel: dulces al alma y salud para los huesos."),
    ("Proverbios 11:8", "El justo es librado de la angustia, y en su lugar cae el malvado."),
    ("Proverbios 29:11", "El necio da rienda suelta a toda su ira, pero el sabio sabe contenerse."),
    ("Marcos 9:23", "Jesús le dijo: Si puedes creer, al que cree todo le es posible."),
    ("Juan 14:6", "Jesús le dijo: Yo soy el camino, y la verdad, y la vida; nadie viene al Padre sino por mí."),
];

const PT: &[Quote] = &[
    ("Alan Kay", "A melhor maneira de prever o futuro é inventá-lo."),
    ("Bill Gates", "Estamos mudando o mundo com a tecnologia."),
    ("Steve Jobs", "A tecnologia sozinha não basta."),
    ("Steve Jobs", "A melhor maneira de criar valor no século XXI é unir criatividade e tecnologia."),
    ("Steve Jobs", "Todo mundo neste país deveria aprender a programar um computador, porque isso ensina a pensar."),
    ("Steve Jobs", "A inovação é a única forma de vencer."),
    ("Steve Jobs", "De vez em quando surge um produto revolucionário que muda tudo."),
    ("Linus Torvalds", "A maioria dos bons programadores não programa porque espera ser paga ou aplaudida pelo público, mas porque programar é divertido."),
    ("Bill Gates", "Não estamos nem perto de realizar o sonho básico do que o PC pode ser."),
    ("Mark Zuckerberg", "Mova-se rápido e quebre coisas. Se você não está quebrando nada, não está indo rápido o bastante."),
    ("Elon Musk", "Qualquer produto que precise de manual para funcionar está quebrado."),
    ("Alan Kay", "Tecnologia é tudo o que foi inventado depois que você nasceu."),
    ("Grace Hopper", "Um navio no porto está seguro, mas não é para isso que navios são feitos. Vá para o mar e faça coisas novas."),
    ("Grace Hopper", "É mais fácil pedir perdão do que pedir permissão."),
    ("Alan Kay", "Coisas simples devem ser simples; coisas complexas devem ser possíveis."),
    ("Steve Jobs", "Design não é só como algo parece; design é como funciona."),
    ("Bill Gates", "Seus clientes mais insatisfeitos são sua maior fonte de aprendizado."),
    ("Elon Musk", "Quando algo é importante o suficiente, você o faz mesmo que as chances estejam contra você."),
    ("Alan Kay", "Quem leva software realmente a sério deveria fazer o próprio hardware."),
    ("Edsger Dijkstra", "Ciência da computação não trata de computadores mais do que astronomia trata de telescópios."),
    ("Grace Hopper", "Os seres humanos são alérgicos à mudança. Adoram dizer: “Sempre fizemos assim.”"),
    ("Jean Sammet", "Não considero uma linguagem de montagem (mesmo uma sofisticada) uma linguagem de programação."),
    ("Sister Mary Kenneth Keller", "Estamos vivendo uma explosão de informação, e é evidente que a informação não serve para nada se não estiver disponível."),
    ("Tim Berners-Lee", "A Web é mais uma criação social do que técnica."),
    ("Vint Cerf", "A internet é um reflexo da nossa sociedade, e esse espelho vai refletir o que vemos."),
    ("Jeff Bezos", "O que precisamos fazer é sempre nos inclinar para o futuro."),
    ("Satya Nadella", "A verdadeira oportunidade é criar produtos que as pessoas amem e que resolvam problemas reais."),
    ("Donald Knuth", "A propriedade mais importante de um programa é se ele cumpre a intenção do usuário."),
    ("Linus Torvalds", "Se você acha que seus usuários são idiotas, só idiotas vão usá-lo."),
    ("Elon Musk", "Aqui, falhar é uma opção. Se as coisas não estão falhando, você não está inovando o suficiente."),
    ("Provérbios 1:7", "O temor do Senhor é o princípio do conhecimento; os insensatos desprezam a sabedoria e a instrução."),
    ("Provérbios 3:5-6", "Confie no Senhor de todo o seu coração e não se apoie em seu próprio entendimento; reconheça o Senhor em todos os seus caminhos, e ele endireitará as suas veredas."),
    ("Provérbios 2:6", "Pois o Senhor dá a sabedoria; de sua boca procedem o conhecimento e o entendimento."),
    ("Provérbios 4:7", "O princípio da sabedoria é: adquire a sabedoria; sim, com tudo o que possuis adquire o entendimento."),
    ("Provérbios 16:16", "Quanto melhor é adquirir a sabedoria do que o ouro, e o entendimento do que a prata!"),
    ("Provérbios 20:18", "Os planos se firmam com conselho; faça a guerra com orientação."),
    ("Provérbios 21:5", "Os planos do diligente levam à fartura, assim como a pressa leva à pobreza."),
    ("Provérbios 16:3", "Confie ao Senhor tudo o que você faz, e os seus planos serão bem-sucedidos."),
    ("Provérbios 12:14", "Palavras sábias trazem muitos benefícios, e o trabalho duro traz recompensa."),
    ("Provérbios 10:14", "Os sábios guardam o conhecimento, mas a boca do tolo atrai a ruína."),
    ("Provérbios 16:18", "A soberba precede a ruína, e a altivez do espírito precede a queda."),
    ("Provérbios 15:1", "A resposta branda desvia o furor, mas a palavra dura suscita a ira."),
    ("Provérbios 27:17", "Como o ferro afia o ferro, assim o homem afia o seu companheiro."),
    ("Provérbios 4:23", "Acima de tudo, guarde o seu coração, pois dele depende toda a sua vida."),
    ("Provérbios 18:21", "A língua tem poder sobre a vida e sobre a morte; quem a ama comerá do seu fruto."),
    ("Provérbios 15:14", "O sábio tem fome de conhecimento, mas o tolo se alimenta de tolice."),
    ("Provérbios 13:4", "O preguiçoso deseja e nada consegue, mas o diligente prospera."),
    ("Provérbios 9:10", "O temor do Senhor é o princípio da sabedoria, e conhecer o Santo é entendimento."),
    ("Provérbios 3:15", "Ela é mais preciosa do que rubis; nada do que você deseja se compara a ela."),
    ("Provérbios 3:13", "Feliz quem encontra a sabedoria, quem obtém o entendimento."),
    ("Provérbios 3:17", "Os seus caminhos são agradáveis, e todas as suas veredas são paz."),
    ("Provérbios 3:18", "Ela é árvore de vida para quem a abraça; felizes os que a retêm."),
    ("Provérbios 4:5", "Adquira sabedoria, adquira entendimento; não se esqueça das minhas palavras nem se afaste delas."),
    ("Provérbios 4:18", "O caminho dos justos é como a luz da aurora, que brilha cada vez mais até ser dia perfeito."),
    ("Provérbios 23:12", "Aplique o coração à instrução e os ouvidos às palavras do conhecimento."),
    ("Provérbios 3:27", "Não deixe de fazer o bem a quem o merece, quando estiver ao seu alcance fazê-lo."),
    ("Provérbios 17:22", "O coração alegre é bom remédio, mas o espírito abatido seca os ossos."),
    ("Provérbios 15:13", "O coração alegre aformoseia o rosto, mas a dor do coração abate o espírito."),
    ("Provérbios 16:24", "Palavras agradáveis são como favo de mel: doces para a alma e saúde para os ossos."),
    ("Provérbios 11:8", "O justo é livrado da angústia, e o ímpio cai no lugar dele."),
    ("Provérbios 29:11", "O tolo dá vazão a toda a sua ira, mas o sábio a domina."),
    ("Marcos 9:23", "E Jesus disse-lhe: Se tu podes crer, tudo é possível ao que crê."),
    ("João 14:6", "Respondeu Jesus: Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai a não ser por mim."),
];

const JA: &[Quote] = &[
    ("Alan Kay", "未来を予測する最善の方法は、それを発明することだ。"),
    ("Bill Gates", "私たちはテクノロジーで世界を変えている。"),
    ("Steve Jobs", "テクノロジーだけでは十分ではない。"),
    ("Steve Jobs", "21世紀に価値を生み出す最善の方法は、創造性とテクノロジーを結びつけることだ。"),
    ("Steve Jobs", "この国の誰もがプログラミングを学ぶべきだ。考え方を教えてくれるからだ。"),
    ("Steve Jobs", "イノベーションこそが勝つ唯一の道だ。"),
    ("Steve Jobs", "ときどき、すべてを変えてしまう革命的な製品が現れる。"),
    ("Linus Torvalds", "優れたプログラマーの多くは、報酬や称賛を期待してプログラミングをするのではない。プログラミングが楽しいからするのだ。"),
    ("Bill Gates", "PC にできることの基本的な夢は、まだ実現にはほど遠い。"),
    ("Mark Zuckerberg", "素早く動き、破壊せよ。何も壊していないなら、十分に速く動いていない。"),
    ("Elon Musk", "動かすのにマニュアルが必要な製品は、壊れている。"),
    ("Alan Kay", "テクノロジーとは、あなたが生まれた後に発明されたもののすべてだ。"),
    ("Grace Hopper", "港にいる船は安全だが、船はそのために造られたのではない。海へ出て、新しいことをせよ。"),
    ("Grace Hopper", "許可を求めるより、後で許しを請うほうが簡単だ。"),
    ("Alan Kay", "単純なことは単純に、複雑なことは可能に。"),
    ("Steve Jobs", "デザインとは、見た目や感触だけではない。どう機能するかだ。"),
    ("Bill Gates", "最も不満を持つ顧客こそ、最大の学びの源である。"),
    ("Elon Musk", "本当に重要なことなら、たとえ分が悪くても実行する。"),
    ("Alan Kay", "ソフトウェアに本気で取り組む人は、自分でハードウェアを作るべきだ。"),
    ("Edsger Dijkstra", "計算機科学が計算機についてではないのは、天文学が望遠鏡についてではないのと同じだ。"),
    ("Grace Hopper", "人間は変化にアレルギーがある。「ずっとこのやり方でやってきた」と言うのが大好きなのだ。"),
    ("Jean Sammet", "アセンブリ言語は（どれほど洗練されたものでも）プログラミング言語だとは考えない。"),
    ("Sister Mary Kenneth Keller", "私たちは情報爆発のただ中にいる。そして情報は、利用できなければ何の役にも立たないことは明らかだ。"),
    ("Tim Berners-Lee", "Web は技術的な創造物というより、社会的な創造物だ。"),
    ("Vint Cerf", "インターネットは社会を映す鏡であり、その鏡は私たちが見ているものを映し出す。"),
    ("Jeff Bezos", "私たちがすべきことは、常に未来に向かって身を乗り出すことだ。"),
    ("Satya Nadella", "本当の機会とは、人々に愛され、現実の問題を解決する製品を作ることだ。"),
    ("Donald Knuth", "プログラムで最も重要なのは、利用者の意図を達成できるかどうかだ。"),
    ("Linus Torvalds", "ユーザーを愚かだと思えば、愚かな人しか使わなくなる。"),
    ("Elon Musk", "ここでは失敗は選択肢の一つだ。何も失敗していないなら、イノベーションが足りない。"),
    ("箴言 1:7", "主を畏れることは知識の初め。愚かな者は知恵と諭しを侮る。"),
    ("箴言 3:5-6", "心を尽くして主に信頼し、自分の悟りに頼るな。あなたの道をことごとく主に知らせよ。そうすれば主はあなたの道筋をまっすぐにされる。"),
    ("箴言 2:6", "主が知恵を授け、主の口から知識と英知が出るからだ。"),
    ("箴言 4:7", "知恵の初めとして、知恵を得よ。あなたの得たすべてのものを尽くして、悟りを得よ。"),
    ("箴言 16:16", "知恵を得ることは金にまさり、悟りを得ることは銀よりも望ましい。"),
    ("箴言 20:18", "計画は助言によって固められる。戦いは指導を得て行え。"),
    ("箴言 21:5", "勤勉な人の計画は豊かさをもたらし、焦る者は欠乏に至る。"),
    ("箴言 16:3", "あなたのわざを主にゆだねよ。そうすれば、あなたの計画は成就する。"),
    ("箴言 12:14", "知恵ある言葉は多くの益をもたらし、勤勉な働きは報いをもたらす。"),
    ("箴言 10:14", "知恵ある者は知識をたくわえ、愚かな者の口は滅びを招く。"),
    ("箴言 16:18", "高ぶりは滅びに先立ち、傲慢な心は倒れに先立つ。"),
    ("箴言 15:1", "柔らかな答えは憤りを静め、激しい言葉は怒りを引き起こす。"),
    ("箴言 27:17", "鉄は鉄をとぐ。人はその友によって磨かれる。"),
    ("箴言 4:23", "何を守るよりも、あなたの心を守れ。命の泉はそこから湧き出る。"),
    ("箴言 18:21", "死も生も舌の力の中にある。舌を愛する者はその実を食べる。"),
    ("箴言 15:14", "賢い人の心は知識を求め、愚かな者の口は愚かさを糧とする。"),
    ("箴言 13:4", "怠け者は欲しても得られず、勤勉な者は豊かになる。"),
    ("箴言 9:10", "主を畏れることは知恵の初め、聖なる方を知ることは悟りである。"),
    ("箴言 3:15", "知恵は真珠よりも尊く、あなたの望むどんなものも、これに比べることはできない。"),
    ("箴言 3:13", "幸いなるかな、知恵を見いだす人、悟りを得る人。"),
    ("箴言 3:17", "その道は楽しい道、その道筋はすべて平安である。"),
    ("箴言 3:18", "知恵は、これをつかむ者には命の木、これを保つ者は幸いである。"),
    ("箴言 4:5", "知恵を得よ、悟りを得よ。わたしの言葉を忘れず、それから離れるな。"),
    ("箴言 4:18", "正しい者の道は夜明けの光のようだ。いよいよ輝きを増して真昼となる。"),
    ("箴言 23:12", "あなたの心を諭しに向け、耳を知識の言葉に傾けよ。"),
    ("箴言 3:27", "善を行うべき相手に、それを拒むな。あなたの手にその力があるときには。"),
    ("箴言 17:22", "喜びに満ちた心は良い薬、打ちひしがれた霊は骨を枯らす。"),
    ("箴言 15:13", "喜びに満ちた心は顔を明るくし、心の痛みは霊を打ちひしぐ。"),
    ("箴言 16:24", "快い言葉は蜂蜜、魂に甘く、骨を癒やす。"),
    ("箴言 11:8", "正しい者は苦難から救われ、代わりに悪しき者がそこに陥る。"),
    ("箴言 29:11", "愚かな者は怒りをすべてぶちまけ、知恵ある者はそれを抑える。"),
    ("マルコ 9:23", "イエスは言われた。できれば、と言うのか。信じる者には、どんなことでもできる。"),
    ("ヨハネ 14:6", "イエスは言われた。わたしは道であり、真理であり、命である。わたしを通らなければ、だれも父のもとに行くことができない。"),
];

const ZH: &[Quote] = &[
    ("Alan Kay", "预测未来最好的方法就是去创造它。"),
    ("Bill Gates", "我们正在用技术改变世界。"),
    ("Steve Jobs", "仅有技术是不够的。"),
    ("Steve Jobs", "在21世纪创造价值的最好方法，是把创造力与技术结合起来。"),
    ("Steve Jobs", "这个国家的每个人都应该学习编程，因为它教会你如何思考。"),
    ("Steve Jobs", "创新是取胜的唯一途径。"),
    ("Steve Jobs", "每隔一段时间，就会出现一款改变一切的革命性产品。"),
    ("Linus Torvalds", "大多数优秀的程序员编程，不是因为期待报酬或公众的赞誉，而是因为编程很有趣。"),
    ("Bill Gates", "关于个人电脑能成为什么，我们离实现那个基本梦想还差得很远。"),
    ("Mark Zuckerberg", "快速行动，打破常规。如果你没有打破什么，说明你动得还不够快。"),
    ("Elon Musk", "任何需要说明书才能使用的产品都是有缺陷的。"),
    ("Alan Kay", "所谓技术，就是你出生之后才发明的一切东西。"),
    ("Grace Hopper", "船停在港口是安全的，但造船不是为了这个。扬帆出海，去做新的事情。"),
    ("Grace Hopper", "请求原谅比请求许可更容易。"),
    ("Alan Kay", "简单的事应当简单，复杂的事应当可行。"),
    ("Steve Jobs", "设计不只是外观和感觉，设计是它如何运作。"),
    ("Bill Gates", "最不满意的客户，是你最宝贵的学习来源。"),
    ("Elon Musk", "当一件事足够重要时，即使胜算不大，你也要去做。"),
    ("Alan Kay", "真正认真对待软件的人，应该自己制造硬件。"),
    ("Edsger Dijkstra", "计算机科学之于计算机，正如天文学之于望远镜。"),
    ("Grace Hopper", "人类对变化过敏。他们最爱说：“我们一直都是这么做的。”"),
    ("Jean Sammet", "我不认为汇编语言（哪怕是很复杂的那种）算是一种编程语言。"),
    ("Sister Mary Kenneth Keller", "我们正处在信息爆炸之中，而显然，信息如果无法获取，就毫无用处。"),
    ("Tim Berners-Lee", "万维网与其说是技术的产物，不如说是社会的产物。"),
    ("Vint Cerf", "互联网是我们社会的一面镜子，这面镜子会映照出我们所看到的一切。"),
    ("Jeff Bezos", "我们要做的，就是始终向未来倾身。"),
    ("Satya Nadella", "真正的机会，是打造人们喜爱并能解决实际问题的产品。"),
    ("Donald Knuth", "程序最重要的属性，是它是否实现了用户的意图。"),
    ("Linus Torvalds", "如果你把用户当傻瓜，就只有傻瓜会用它。"),
    ("Elon Musk", "在这里，失败是一种选择。如果没有失败，说明你创新得还不够。"),
    ("箴言 1:7", "敬畏耶和华是知识的开端，愚妄人藐视智慧和训诲。"),
    ("箴言 3:5-6", "你要专心仰赖耶和华，不可倚靠自己的聪明；在你一切所行的事上都要认定他，他必指引你的路。"),
    ("箴言 2:6", "因为耶和华赐人智慧；知识和聪明都由他口而出。"),
    ("箴言 4:7", "智慧为首，所以要得智慧；在你一切所得之内必得聪明。"),
    ("箴言 16:16", "得智慧胜似得金子；选聪明强如选银子。"),
    ("箴言 20:18", "计谋都凭商议立定；打仗要凭智谋。"),
    ("箴言 21:5", "殷勤筹划的，足致丰裕；行事急躁的，都必缺乏。"),
    ("箴言 16:3", "你所做的，要交托耶和华，你所谋的，就必成立。"),
    ("箴言 12:14", "智慧的言语带来许多益处，勤劳的工作带来回报。"),
    ("箴言 10:14", "智慧人积存知识；愚妄人的口速致败坏。"),
    ("箴言 16:18", "骄傲在败坏以先，狂心在跌倒之前。"),
    ("箴言 15:1", "回答柔和，使怒消退；言语暴戾，触动怒气。"),
    ("箴言 27:17", "铁磨铁，磨出刃来；朋友相感，也是如此。"),
    ("箴言 4:23", "你要保守你心，胜过保守一切，因为一生的果效是由心发出。"),
    ("箴言 18:21", "生死在舌头的权下，喜爱它的，必吃它所结的果子。"),
    ("箴言 15:14", "聪明人的心寻求知识；愚昧人的口吃愚昧。"),
    ("箴言 13:4", "懒惰人羡慕，却无所得；殷勤人必得丰裕。"),
    ("箴言 9:10", "敬畏耶和华是智慧的开端，认识至圣者便是聪明。"),
    ("箴言 3:15", "智慧比珍珠宝贵；你一切所喜爱的，都不足与比较。"),
    ("箴言 3:13", "得智慧、得聪明的，这人便为有福。"),
    ("箴言 3:17", "她的道是安乐，她的路全是平安。"),
    ("箴言 3:18", "她与持守她的作生命树；持定她的俱各有福。"),
    ("箴言 4:5", "要得智慧，要得聪明，不可忘记，也不可偏离我口中的言语。"),
    ("箴言 4:18", "义人的路好像黎明的光，越照越明，直到日午。"),
    ("箴言 23:12", "你要专心领受训诲，侧耳听从知识的言语。"),
    ("箴言 3:27", "你手若有行善的力量，不可推辞，就当向那应得的人施行。"),
    ("箴言 17:22", "喜乐的心乃是良药；忧伤的灵使骨枯干。"),
    ("箴言 15:13", "心中喜乐，面带笑容；心里忧愁，灵被损伤。"),
    ("箴言 16:24", "良言如同蜂房，使心觉甘甜，使骨得医治。"),
    ("箴言 11:8", "义人得脱离患难，有恶人来代替他。"),
    ("箴言 29:11", "愚妄人怒气全发；智慧人忍气含怒。"),
    ("马可福音 9:23", "耶稣对他说：你若能信，在信的人，凡事都能。"),
    ("约翰福音 14:6", "耶稣说：我就是道路、真理、生命；若不藉着我，没有人能到父那里去。"),
];

const FR: &[Quote] = &[
    ("Alan Kay", "La meilleure façon de prédire l’avenir, c’est de l’inventer."),
    ("Bill Gates", "Nous changeons le monde grâce à la technologie."),
    ("Steve Jobs", "La technologie seule ne suffit pas."),
    ("Steve Jobs", "La meilleure façon de créer de la valeur au XXIe siècle est d’unir la créativité et la technologie."),
    ("Steve Jobs", "Tout le monde dans ce pays devrait apprendre à programmer un ordinateur, parce que cela apprend à penser."),
    ("Steve Jobs", "L’innovation est la seule façon de gagner."),
    ("Steve Jobs", "De temps en temps apparaît un produit révolutionnaire qui change tout."),
    ("Linus Torvalds", "La plupart des bons programmeurs ne programment pas parce qu’ils espèrent être payés ou admirés du public, mais parce que programmer est amusant."),
    ("Bill Gates", "Nous sommes loin d’avoir réalisé le rêve fondamental de ce que peut être le PC."),
    ("Mark Zuckerberg", "Allez vite et cassez des choses. Si vous ne cassez rien, vous n’allez pas assez vite."),
    ("Elon Musk", "Tout produit qui a besoin d’un mode d’emploi pour fonctionner est défaillant."),
    ("Alan Kay", "La technologie, c’est tout ce qui a été inventé après votre naissance."),
    ("Grace Hopper", "Un navire au port est en sécurité, mais ce n’est pas pour cela qu’on construit des navires. Prenez la mer et faites des choses nouvelles."),
    ("Grace Hopper", "Il est plus facile de demander pardon que de demander la permission."),
    ("Alan Kay", "Les choses simples doivent être simples ; les choses complexes doivent être possibles."),
    ("Steve Jobs", "Le design, ce n’est pas seulement l’apparence et le ressenti. Le design, c’est comment ça fonctionne."),
    ("Bill Gates", "Vos clients les plus mécontents sont votre plus grande source d’apprentissage."),
    ("Elon Musk", "Quand une chose est vraiment importante, on la fait même si les chances ne sont pas en notre faveur."),
    ("Alan Kay", "Ceux qui prennent vraiment le logiciel au sérieux devraient fabriquer leur propre matériel."),
    ("Edsger Dijkstra", "L’informatique n’est pas plus la science des ordinateurs que l’astronomie n’est celle des télescopes."),
    ("Grace Hopper", "Les humains sont allergiques au changement. Ils adorent dire : « On a toujours fait comme ça. »"),
    ("Jean Sammet", "Je ne considère pas un langage d’assemblage (même sophistiqué) comme un langage de programmation."),
    ("Sister Mary Kenneth Keller", "Nous vivons une explosion de l’information, et il est évident que l’information ne sert à rien si elle n’est pas accessible."),
    ("Tim Berners-Lee", "Le Web est davantage une création sociale qu’une création technique."),
    ("Vint Cerf", "Internet est un reflet de notre société, et ce miroir va refléter ce que nous voyons."),
    ("Jeff Bezos", "Ce que nous devons faire, c’est toujours nous tourner vers l’avenir."),
    ("Satya Nadella", "La vraie opportunité est de créer des produits que les gens aiment et qui résolvent de vrais problèmes."),
    ("Donald Knuth", "La propriété la plus importante d’un programme est de réaliser l’intention de son utilisateur."),
    ("Linus Torvalds", "Si vous pensez que vos utilisateurs sont des idiots, seuls des idiots l’utiliseront."),
    ("Elon Musk", "Ici, l’échec est une option. Si rien n’échoue, vous n’innovez pas assez."),
    ("Proverbes 1:7", "La crainte de l’Éternel est le commencement de la science ; les insensés méprisent la sagesse et l’instruction."),
    ("Proverbes 3:5-6", "Confie-toi en l’Éternel de tout ton cœur, et ne t’appuie pas sur ta sagesse ; reconnais-le dans toutes tes voies, et il aplanira tes sentiers."),
    ("Proverbes 2:6", "Car l’Éternel donne la sagesse ; de sa bouche sortent la connaissance et l’intelligence."),
    ("Proverbes 4:7", "Voici le commencement de la sagesse : acquiers la sagesse, et avec tout ce que tu possèdes acquiers l’intelligence."),
    ("Proverbes 16:16", "Combien acquérir la sagesse vaut mieux que l’or ! Acquérir l’intelligence vaut mieux que l’argent."),
    ("Proverbes 20:18", "Les projets s’affermissent par le conseil ; fais la guerre avec prudence."),
    ("Proverbes 21:5", "Les projets de l’homme diligent mènent à l’abondance, comme la précipitation mène à la disette."),
    ("Proverbes 16:3", "Recommande à l’Éternel tes œuvres, et tes projets réussiront."),
    ("Proverbes 12:14", "Les paroles sages apportent bien des bienfaits, et le travail porte sa récompense."),
    ("Proverbes 10:14", "Les sages tiennent la science en réserve, mais la bouche de l’insensé attire la ruine."),
    ("Proverbes 16:18", "L’arrogance précède la ruine, et l’orgueil précède la chute."),
    ("Proverbes 15:1", "Une réponse douce calme la fureur, mais une parole dure excite la colère."),
    ("Proverbes 27:17", "Comme le fer aiguise le fer, ainsi un homme aiguise un autre homme."),
    ("Proverbes 4:23", "Garde ton cœur plus que toute autre chose, car de lui viennent les sources de la vie."),
    ("Proverbes 18:21", "La langue a pouvoir de vie et de mort ; qui l’aime en mangera les fruits."),
    ("Proverbes 15:14", "Le sage a faim de connaissance, tandis que l’insensé se nourrit de folie."),
    ("Proverbes 13:4", "Le paresseux désire et n’obtient rien, mais le diligent prospère."),
    ("Proverbes 9:10", "La crainte de l’Éternel est le commencement de la sagesse, et la connaissance du Saint, c’est l’intelligence."),
    ("Proverbes 3:15", "Elle est plus précieuse que les perles ; rien de ce que tu désires ne l’égale."),
    ("Proverbes 3:13", "Heureux celui qui trouve la sagesse, celui qui acquiert l’intelligence."),
    ("Proverbes 3:17", "Ses voies sont des voies agréables, et tous ses sentiers sont paisibles."),
    ("Proverbes 3:18", "Elle est un arbre de vie pour ceux qui la saisissent ; heureux ceux qui la retiennent."),
    ("Proverbes 4:5", "Acquiers la sagesse, acquiers l’intelligence ; n’oublie pas mes paroles et ne t’en détourne pas."),
    ("Proverbes 4:18", "Le sentier des justes est comme la lumière de l’aurore, dont l’éclat grandit jusqu’au plein jour."),
    ("Proverbes 23:12", "Ouvre ton cœur à l’instruction, et tes oreilles aux paroles de la science."),
    ("Proverbes 3:27", "Ne refuse pas un bienfait à celui qui y a droit, quand tu as le pouvoir de l’accorder."),
    ("Proverbes 17:22", "Un cœur joyeux est un bon remède, mais un esprit abattu dessèche les os."),
    ("Proverbes 15:13", "Un cœur joyeux rend le visage serein, mais quand le cœur est triste, l’esprit est abattu."),
    ("Proverbes 16:24", "Les paroles agréables sont un rayon de miel, douces pour l’âme et salutaires pour le corps."),
    ("Proverbes 11:8", "Le juste est délivré de la détresse, et le méchant prend sa place."),
    ("Proverbes 29:11", "L’insensé donne libre cours à toute sa colère, mais le sage la retient."),
    ("Marc 9:23", "Jésus lui dit : Si tu peux croire, tout est possible à celui qui croit."),
    ("Jean 14:6", "Jésus lui dit : Je suis le chemin, la vérité et la vie. Nul ne vient au Père que par moi."),
];

#[cfg(test)]
mod tests {
    use super::*;
    use crate::i18n::Language;

    #[test]
    fn every_language_has_a_nonempty_localized_pool() {
        for lang in [
            Language::English,
            Language::Spanish,
            Language::Portuguese,
            Language::Japanese,
            Language::Chinese,
            Language::French,
        ] {
            let q = quotes(lang);
            assert!(!q.is_empty(), "{lang:?} quote pool is empty");
            // No entry may be blank.
            assert!(
                q.iter().all(|(a, t)| !a.is_empty() && !t.is_empty()),
                "{lang:?} has a blank quote/author"
            );
        }
        // Every language carries the whole pool, in English's order.
        let en = quotes(Language::English);
        for lang in [Language::Spanish, Language::Portuguese, Language::Japanese, Language::Chinese, Language::French] {
            let q = quotes(lang);
            assert_eq!(q.len(), en.len(), "{lang:?} is missing quotes");
            for ((ea, et), (a, t)) in en.iter().zip(q) {
                // Scripture keeps its chapter and verse; people keep their name.
                let reference = |r: &str| r.rsplit(' ').next().map(str::to_owned);
                if ea.contains(':') {
                    assert_eq!(reference(ea), reference(a), "{lang:?}: {ea} vs {a}");
                } else {
                    assert_eq!(ea, a, "{lang:?}: author order differs");
                }
                assert_ne!(et, t, "{lang:?}: {ea} is not translated");
            }
        }
        // Non-English pools must actually differ from English (localised).
        assert_ne!(
            quotes(Language::Spanish)[0].1,
            quotes(Language::English)[0].1
        );
        assert_ne!(
            quotes(Language::French)[0].1,
            quotes(Language::English)[0].1
        );
    }
}
