// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Emerson Lopes and PowerRustCOBOL contributors

//! `rust_manifest.md` in the destination folder (spec 044 R24–R26).
//!
//! Reuse map: called from `build_core` step 11c — the same delivery step that
//! places the binary, assets, and license notices in `dist/`.

use std::path::{Path, PathBuf};

use crate::project::RegisteredCrate;

pub const MANIFEST_FILE: &str = "rust_manifest.md";

/// R24/R25 — write the manifest when there are crates, remove a stale one
/// when there are none: the delivered folder never claims third-party code
/// the binary does not contain.
pub fn write(
    dest_dir: &Path,
    project_name: &str,
    crates: &[RegisteredCrate],
) -> Result<Option<PathBuf>, String> {
    let path = dest_dir.join(MANIFEST_FILE);
    if crates.is_empty() {
        if path.exists() {
            std::fs::remove_file(&path)
                .map_err(|e| format!("cannot remove stale {}: {e}", path.display()))?;
        }
        return Ok(None);
    }
    std::fs::create_dir_all(dest_dir)
        .map_err(|e| format!("cannot create {}: {e}", dest_dir.display()))?;
    std::fs::write(&path, render(project_name, crates))
        .map_err(|e| format!("cannot write {}: {e}", path.display()))?;
    Ok(Some(path))
}

/// R24 columns exactly: name, URL, exact built version. R26: a build
/// artefact with a generated-by banner, matching the generated-code
/// convention — never hand-edited.
fn render(project_name: &str, crates: &[RegisteredCrate]) -> String {
    let mut s = String::new();
    s.push_str(&format!(
        "<!-- Generated by PowerRustCOBOL — build artefact, do not edit.\n\
         \u{20}    Regenerated on every successful build of {project_name}. -->\n\n"
    ));
    s.push_str(&format!("# Rust crate manifest — {project_name}\n\n"));
    s.push_str(
        "Third-party Rust crates compiled into this application's binary:\n\n\
         | Crate | Version | URL |\n|-------|---------|-----|\n",
    );
    let mut sorted: Vec<&RegisteredCrate> = crates.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    for c in sorted {
        s.push_str(&format!("| {} | {} | {} |\n", c.name, c.version, c.url));
    }
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn reg(name: &str, version: &str) -> RegisteredCrate {
        RegisteredCrate {
            name: name.into(),
            requirement: String::new(),
            version: version.into(),
            features: vec![],
            url: format!("https://crates.io/crates/{name}"),
        }
    }

    /// R24 — every crate appears with name, version, and URL; R26 — the
    /// banner marks it generated.
    #[test]
    fn manifest_lists_name_version_url() {
        let text = render("Demo", &[reg("csv", "1.3.1"), reg("serde", "1.0.219")]);
        assert!(text.contains("Generated by PowerRustCOBOL"));
        assert!(text.contains("| csv | 1.3.1 | https://crates.io/crates/csv |"));
        assert!(text.contains("| serde | 1.0.219 | https://crates.io/crates/serde |"));
    }

    /// R25 — zero crates removes a stale manifest instead of leaving a lie.
    #[test]
    fn empty_set_removes_the_stale_manifest() {
        let dir = std::env::temp_dir().join(format!("prc044-dist-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let written = write(&dir, "Demo", &[reg("csv", "1.3.1")]).unwrap();
        assert!(written.is_some_and(|p| p.exists()));
        let removed = write(&dir, "Demo", &[]).unwrap();
        assert!(removed.is_none());
        assert!(!dir.join(MANIFEST_FILE).exists());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
