[project]
name = "DonutChart Test"
version = "1.0.0"
main = "generated/donut-chart.cbl"
copyright = ""
license_model = ""
license_text = ""

[files]
sources = []
forms = ["forms/donut-chart.cfrm"]
assets = []
documentation = []
generated = ["generated/donut-chart.cbl"]
indexed = []

[runtime]
fixed_format = false

[ide]
theme = ""
background_image = ""
background_opacity = 70
