// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Emerson Lopes and PowerRustCOBOL contributors
//
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

//! `EXEC RUST` block dispatch (spec 041).
//!
//! # What this is
//!
//! An `EXEC RUST` block is **compiled**, not interpreted. `cobolt-compiler`
//! emits each block as a real Rust function into the crate it already builds
//! with `cargo`, and the generated `main.rs` registers those functions here
//! before the interpreter runs. This module's whole job is to find the function
//! for a block and call it with the run's context, containing any panic.
//!
//! # What this replaced, and why
//!
//! Until spec 041 this module *interpreted* a four-form micro-language —
//! compound assignment, simple assignment, `let` as a **no-op**, and integer
//! arithmetic — and, critically:
//!
//! ```text
//! // Unknown statement form — log and continue (don't hard-fail).
//! tracing::debug!("EXEC RUST: unrecognised statement: {src:?}");
//! ```
//!
//! Anything it did not recognise was written to a debug log and skipped. A
//! block of real Rust therefore **succeeded while doing nothing at all** — no
//! error, no output, nothing to diagnose. Removing that silence is as much the
//! point of spec 041 as adding the capability (R11), which is why an
//! unregistered block id here is a hard [`RuntimeError::ExecRustError`] and
//! never a quiet return.
//!
//! # No FFI
//!
//! Generated blocks are compiled into the same binary as this runtime, so a
//! call is ordinary Rust: no `extern "C"`, no C ABI, no dynamic loading.
//! [`contain`] is all that R12/R13 require.

use std::collections::HashMap;

use cobolt_ast::stmt::Stmt;

use crate::{
    environment::CobolEnvironment, error::RuntimeError, objects::ObjectRegistry,
    rust_bridge::RustBridge,
};

// ── The context a block receives ─────────────────────────────────────────────

/// What a compiled block is given: the COBOL environment, the form/control
/// registry, and the Rust object bridge.
///
/// The three are different stores and a block needs all of them:
///
/// * `env` holds the DATA DIVISION items — including, for an
///   `OBJECT REFERENCE` item, the **handle id**, which is what its storage
///   actually contains;
/// * `bridge` holds the object that id refers to, as a genuine `std` value.
///   That pairing is what lets a generated preamble hand the block a real
///   `String` rather than a dynamically-typed stand-in (spec 041 R4, R7);
/// * `objects` holds forms and controls, so a block can read and write control
///   properties.
///
/// `bridge` was missing until T8 and the omission was not cosmetic: without it
/// a generated block could see the handle id in `env` but nothing it pointed
/// at, so no bound item could be reached at all.
pub struct ExecRustContext<'a> {
    pub env: &'a mut CobolEnvironment,
    pub objects: &'a mut ObjectRegistry,
    pub bridge: &'a mut RustBridge,
}

/// One compiled block. Generated by `cobolt-compiler`; never written by hand.
pub type ExecRustFn = fn(&mut ExecRustContext<'_>);

/// Block id → compiled function, filled by the generated `main.rs` at startup.
///
/// All blocks in a program share one registry and one run, which is what gives
/// them a single shared context (R9).
#[derive(Default)]
pub struct ExecRustRegistry {
    blocks: HashMap<u32, ExecRustFn>,
}

impl ExecRustRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register the compiled function for `block_id`.
    pub fn register(&mut self, block_id: u32, f: ExecRustFn) {
        self.blocks.insert(block_id, f);
    }

    pub fn get(&self, block_id: u32) -> Option<ExecRustFn> {
        self.blocks.get(&block_id).copied()
    }

    pub fn is_empty(&self) -> bool {
        self.blocks.is_empty()
    }

    pub fn len(&self) -> usize {
        self.blocks.len()
    }
}

// ── Panic containment (spec 041 R12, R13) ────────────────────────────────────

/// Run a compiled block body, turning a panic into a [`RuntimeError::RustPanic`]
/// instead of letting it unwind out of the interpreter.
///
/// The message is plain text — the panic payload — so `DISPLAY` of the name
/// bound by `CATCH RUST-EXCEPTION` is readable without picking substrings out
/// of it (R23).
pub(crate) fn contain<T>(f: impl FnOnce() -> T) -> Result<T, RuntimeError> {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)) {
        Ok(value) => Ok(value),
        Err(payload) => {
            // A panic payload is `&str` or `String` in practice; anything else
            // is reported as such rather than silently becoming an empty
            // message, which would be undiagnosable.
            let message = payload
                .downcast_ref::<&str>()
                .map(|s| (*s).to_string())
                .or_else(|| payload.downcast_ref::<String>().cloned())
                .unwrap_or_else(|| "panic with a non-string payload".to_string());
            Err(RuntimeError::RustPanic { message })
        }
    }
}

// ── Public entry point ────────────────────────────────────────────────────────

/// Execute an `EXEC RUST` block by calling its compiled function.
///
/// Fails loudly when no function is registered for the block: that means the
/// program was run without being built, or codegen and the runtime disagree
/// about ids. Either way it is a fault, not something to skip (R11).
pub fn execute(
    stmt: &Stmt,
    env: &mut CobolEnvironment,
    objects: &mut ObjectRegistry,
    bridge: &mut RustBridge,
    registry: &ExecRustRegistry,
) -> Result<(), RuntimeError> {
    let (block_id, span) = match stmt {
        Stmt::ExecRust { block_id, span, .. } => (*block_id, *span),
        _ => {
            return Err(RuntimeError::ExecRustError {
                message: "internal: execute called on a statement that is not EXEC RUST".into(),
                span: stmt.span(),
            })
        }
    };

    let Some(block) = registry.get(block_id) else {
        return Err(RuntimeError::ExecRustError {
            message: format!(
                "EXEC RUST block {block_id} has no compiled function — build the \
                 project before running it"
            ),
            span,
        });
    };

    let mut ctx = ExecRustContext {
        env,
        objects,
        bridge,
    };
    contain(move || block(&mut ctx))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// R12/R13 — a panic in generated Rust becomes a catchable runtime error
    /// and never unwinds out of the interpreter.
    #[test]
    fn a_panic_becomes_a_rust_panic_error() {
        let ok = contain(|| 2 + 2);
        assert_eq!(ok.unwrap(), 4, "a normal return must pass straight through");

        let err = contain(|| -> i32 { panic!("index out of range") });
        match err {
            Err(RuntimeError::RustPanic { message }) => assert!(
                message.contains("index out of range"),
                "the payload was lost: {message}"
            ),
            other => panic!("expected RustPanic, got {other:?}"),
        }

        // A `String` payload survives too — `panic!("{}", s)` produces one.
        let err = contain(|| -> i32 { panic!("{}", String::from("boom")) });
        assert!(matches!(
            err,
            Err(RuntimeError::RustPanic { ref message }) if message.contains("boom")
        ));
    }

    /// A panic is NOT a `UserException`; that difference is what stops a plain
    /// `CATCH EXCEPTION` from swallowing it (R24).
    #[test]
    fn a_contained_panic_is_not_a_user_exception() {
        let err = contain(|| -> i32 { panic!("boom") }).unwrap_err();
        assert!(
            !matches!(err, RuntimeError::UserException { .. }),
            "a panic must not masquerade as a COBOL exception: {err:?}"
        );
    }

    /// **AC5 / R11 — the regression guard for the defect that started spec 041.**
    ///
    /// The executor this replaced would log an unrecognised statement and
    /// continue, so a block doing real work reported success and did nothing.
    /// An id with no compiled function must now fail, and say why.
    #[test]
    fn an_unregistered_block_fails_loudly() {
        let mut env = CobolEnvironment::new();
        let mut objects = ObjectRegistry::default();
        let mut bridge = RustBridge::new();
        let registry = ExecRustRegistry::new();
        let stmt = Stmt::ExecRust {
            source: "let anything = 1;".into(),
            referenced_data: Vec::new(),
            block_id: 7,
            span: cobolt_lexer::Span::dummy(),
        };

        let err = execute(&stmt, &mut env, &mut objects, &mut bridge, &registry)
            .expect_err("an unregistered block must not silently succeed");
        match err {
            RuntimeError::ExecRustError { message, .. } => {
                assert!(message.contains("no compiled function"), "{message}");
                assert!(message.contains('7'), "the id should be named: {message}");
            }
            other => panic!("expected ExecRustError, got {other:?}"),
        }
    }

    /// A registered block runs, and its effects are visible afterwards.
    #[test]
    fn a_registered_block_runs() {
        fn body(ctx: &mut ExecRustContext<'_>) {
            ctx.env.set_i64("WS-COUNT", 42);
        }

        let mut env = CobolEnvironment::new();
        let mut objects = ObjectRegistry::default();
        let mut bridge = RustBridge::new();
        let mut registry = ExecRustRegistry::new();
        registry.register(0, body);

        let stmt = Stmt::ExecRust {
            source: String::new(),
            referenced_data: Vec::new(),
            block_id: 0,
            span: cobolt_lexer::Span::dummy(),
        };
        execute(&stmt, &mut env, &mut objects, &mut bridge, &registry)
            .expect("the block should run");
        assert_eq!(
            env.get("WS-COUNT").map(|v| v.as_display_string()),
            Some("42".to_string())
        );
    }

    /// A panicking block is contained, not fatal to the process.
    #[test]
    fn a_panicking_block_yields_a_rust_panic() {
        fn body(_ctx: &mut ExecRustContext<'_>) {
            panic!("block blew up");
        }

        let mut env = CobolEnvironment::new();
        let mut objects = ObjectRegistry::default();
        let mut bridge = RustBridge::new();
        let mut registry = ExecRustRegistry::new();
        registry.register(3, body);

        let stmt = Stmt::ExecRust {
            source: String::new(),
            referenced_data: Vec::new(),
            block_id: 3,
            span: cobolt_lexer::Span::dummy(),
        };
        match execute(&stmt, &mut env, &mut objects, &mut bridge, &registry) {
            Err(RuntimeError::RustPanic { message }) => {
                assert!(message.contains("block blew up"), "{message}")
            }
            other => panic!("expected RustPanic, got {other:?}"),
        }
    }

    /// **The T6 omission this task fixed.** A block reaches a bound
    /// `OBJECT REFERENCE` item by reading its handle id from `env` and the
    /// object itself from `bridge`. Before `bridge` was on the context the id
    /// was reachable and the object was not, so no binding could work at all.
    ///
    /// This is the runtime half of what the generated preamble does: take the
    /// value out, mutate it as a real `String`, put it back.
    #[test]
    fn a_block_reaches_a_bound_object_through_the_bridge() {
        fn body(ctx: &mut ExecRustContext<'_>) {
            let id = ctx.env.get("WS-TEXT").and_then(|v| v.as_i64()).unwrap();
            let mut ws_text: String = ctx.bridge.take_value::<String>(id).unwrap();
            ws_text.push_str(", world");
            ctx.bridge.put_value(id, "Rust.String", ws_text);
        }

        let mut env = CobolEnvironment::new();
        let mut objects = ObjectRegistry::default();
        let mut bridge = RustBridge::new();
        let handle = match bridge
            .create("Rust.String", &[crate::rust_bridge::BridgeValue::Str("hello".into())])
            .unwrap()
        {
            crate::rust_bridge::BridgeValue::Handle(id) => id,
            other => panic!("expected a handle, got {other:?}"),
        };
        env.set_i64("WS-TEXT", handle);

        let mut registry = ExecRustRegistry::new();
        registry.register(1, body);
        let stmt = Stmt::ExecRust {
            source: String::new(),
            referenced_data: vec![cobolt_ast::stmt::ExecRustBinding {
                cobol_name: "WS-TEXT".into(),
                rust_name: "ws_text".into(),
            }],
            block_id: 1,
            span: cobolt_lexer::Span::dummy(),
        };
        execute(&stmt, &mut env, &mut objects, &mut bridge, &registry)
            .expect("the block should run");

        // The mutation is visible to COBOL afterwards, through the same handle.
        let after = bridge.take_value::<String>(handle).expect("still a String");
        assert_eq!(after, "hello, world");
    }
}
