       IDENTIFICATION DIVISION.
       PROGRAM-ID. NUMEDCOM.

       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SPECIAL-NAMES.
           DECIMAL-POINT IS COMMA.

       DATA DIVISION.
       WORKING-STORAGE SECTION.

       01  TEST-COUNTERS.
           05 TESTS-RUN              PIC 9(4) VALUE 0.
           05 TESTS-PASSED           PIC 9(4) VALUE 0.
           05 TESTS-FAILED           PIC 9(4) VALUE 0.

       01  TEST-CONTEXT.
           05 TEST-ID                PIC X(8)  VALUE SPACES.
           05 TEST-NAME              PIC X(60) VALUE SPACES.
           05 ACTUAL-RESULT          PIC X(80) VALUE SPACES.
           05 EXPECTED-RESULT        PIC X(80) VALUE SPACES.

       01  NUMERIC-SOURCES.
           05 SRC-U4                 PIC 9(4)       VALUE ZERO.
           05 SRC-U5                 PIC 9(5)       VALUE ZERO.
           05 SRC-U8                 PIC 9(8)       VALUE ZERO.
           05 SRC-S4                 PIC S9(4)      VALUE ZERO.
           05 SRC-S5                 PIC S9(5)      VALUE ZERO.
           05 SRC-U5V2               PIC 9(5)V99    VALUE ZERO.
           05 SRC-S5V2               PIC S9(5)V99   VALUE ZERO.

           05 SRC-LEAD-SEP           PIC S9(4)
                                      SIGN LEADING SEPARATE
                                      VALUE ZERO.

           05 SRC-TRAIL-SEP          PIC S9(4)
                                      SIGN TRAILING SEPARATE
                                      VALUE ZERO.

           05 SRC-COMP               PIC S9(5)
                                      USAGE COMPUTATIONAL
                                      VALUE ZERO.

           05 SRC-COMP-DEC           PIC S9(5)V99
                                      USAGE COMPUTATIONAL
                                      VALUE ZERO.

           05 SRC-COMP-1             USAGE COMPUTATIONAL-1.
           05 SRC-COMP-2             USAGE COMPUTATIONAL-2.

           05 SRC-COMP-3             PIC S9(5)V99
                                      USAGE COMPUTATIONAL-3
                                      VALUE ZERO.

           05 SRC-COMP-4             PIC S9(5)
                                      USAGE COMPUTATIONAL-4
                                      VALUE ZERO.

           05 SRC-ARITH              PIC S9(7)V99 VALUE ZERO.

       01  EDITED-FIELDS.
           05 E-9999                 PIC 9999.
           05 E-ZZZ9                 PIC ZZZ9.
           05 E-ZZZZ                 PIC ZZZZ.
           05 E-STAR9                PIC ***9.
           05 E-STARS                PIC ****.

           05 E-GROUP-FIX            PIC 9.999.
           05 E-GROUP-Z              PIC ZZ.ZZ9.
           05 E-DEC-FIX              PIC 999,99.
           05 E-DEC-Z                PIC ZZ9,99.

           05 E-PLUS-LEAD            PIC +9999.
           05 E-PLUS-TRAIL           PIC 9999+.
           05 E-MINUS-LEAD           PIC -9999.
           05 E-MINUS-TRAIL          PIC 9999-.

           05 E-CR                   PIC 9999CR.
           05 E-DB                   PIC 9999DB.

           05 E-CURRENCY-FIX         PIC $9999.
           05 E-CURRENCY-FLOAT       PIC $$$$9.
           05 E-PLUS-FLOAT           PIC ++++9.
           05 E-MINUS-FLOAT          PIC ----9.

           05 E-BLANK-INSERT         PIC 99B99.
           05 E-ZERO-INSERT          PIC 9900.
           05 E-SLASH-INSERT         PIC 99/99/9999.

           05 E-COMPLEX-SIGN         PIC $ZZ.ZZ9,99-.
           05 E-COMPLEX-CR           PIC $ZZ.ZZ9,99CR.
           05 E-BLANK-WHEN-ZERO      PIC ZZ9,99
                                      BLANK WHEN ZERO.

       PROCEDURE DIVISION.

       MAIN-PARA.

           DISPLAY "NUMERIC-EDITED PIC TESTS".
           DISPLAY "DECIMAL-POINT IS COMMA".
           DISPLAY "------------------------".

           PERFORM TEST-001-LITERAL-DECIMAL-COMMA.
           PERFORM TEST-002-DISPLAY-DECIMAL-SOURCE.
           PERFORM TEST-003-GROUPING-PERIOD.
           PERFORM TEST-004-ZERO-SUPPRESSION.
           PERFORM TEST-005-STAR-PROTECTION.

           PERFORM TEST-010-LEADING-PLUS-POS.
           PERFORM TEST-011-LEADING-PLUS-NEG.
           PERFORM TEST-012-TRAILING-PLUS-POS.
           PERFORM TEST-013-TRAILING-PLUS-NEG.

           PERFORM TEST-020-LEADING-MINUS-POS.
           PERFORM TEST-021-LEADING-MINUS-NEG.
           PERFORM TEST-022-TRAILING-MINUS-POS.
           PERFORM TEST-023-TRAILING-MINUS-NEG.

           PERFORM TEST-030-CR-POS.
           PERFORM TEST-031-CR-NEG.
           PERFORM TEST-032-DB-POS.
           PERFORM TEST-033-DB-NEG.

           PERFORM TEST-040-CURRENCY-FIXED.
           PERFORM TEST-041-CURRENCY-FLOAT.
           PERFORM TEST-042-FLOATING-PLUS-POS.
           PERFORM TEST-043-FLOATING-PLUS-NEG.
           PERFORM TEST-044-FLOATING-MINUS-POS.
           PERFORM TEST-045-FLOATING-MINUS-NEG.

           PERFORM TEST-050-BLANK-INSERTION.
           PERFORM TEST-051-ZERO-INSERTION.
           PERFORM TEST-052-SLASH-INSERTION.

           PERFORM TEST-060-COMP-SOURCE.
           PERFORM TEST-061-COMP-DECIMAL-SOURCE.
           PERFORM TEST-062-COMP-1-SOURCE.
           PERFORM TEST-063-COMP-2-SOURCE.
           PERFORM TEST-064-COMP-3-SOURCE.
           PERFORM TEST-065-COMP-4-SOURCE.

           PERFORM TEST-070-LEADING-SEPARATE-SOURCE.
           PERFORM TEST-071-TRAILING-SEPARATE-SOURCE.
           PERFORM TEST-072-ARITHMETIC-SOURCE.

           PERFORM TEST-080-COMPLEX-POSITIVE.
           PERFORM TEST-081-COMPLEX-NEGATIVE.
           PERFORM TEST-082-COMPLEX-CR-POSITIVE.
           PERFORM TEST-083-COMPLEX-CR-NEGATIVE.
           PERFORM TEST-084-BLANK-WHEN-ZERO.
           PERFORM TEST-085-BLANK-WHEN-NONZERO.

           DISPLAY "------------------------".
           DISPLAY "TESTS RUN    : " TESTS-RUN.
           DISPLAY "TESTS PASSED : " TESTS-PASSED.
           DISPLAY "TESTS FAILED : " TESTS-FAILED.

           IF TESTS-FAILED = ZERO
               DISPLAY "RESULT       : PASS"
           ELSE
               DISPLAY "RESULT       : FAIL"
           END-IF.

           STOP RUN.

       ASSERT-RESULT.

           ADD 1 TO TESTS-RUN.

           IF ACTUAL-RESULT = EXPECTED-RESULT
               ADD 1 TO TESTS-PASSED
               DISPLAY "PASS " TEST-ID " " TEST-NAME
           ELSE
               ADD 1 TO TESTS-FAILED
               DISPLAY "FAIL " TEST-ID " " TEST-NAME
               DISPLAY "     ACTUAL   = [" ACTUAL-RESULT "]"
               DISPLAY "     EXPECTED = [" EXPECTED-RESULT "]"
           END-IF.

       TEST-001-LITERAL-DECIMAL-COMMA.

           MOVE "T001" TO TEST-ID.
           MOVE "NUMERIC LITERAL WITH DECIMAL COMMA" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123,45 TO E-DEC-FIX.
           MOVE E-DEC-FIX TO ACTUAL-RESULT.
           MOVE "123,45" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-002-DISPLAY-DECIMAL-SOURCE.

           MOVE "T002" TO TEST-ID.
           MOVE "DISPLAY DECIMAL SOURCE TO PIC 999,99" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 12,30 TO SRC-U5V2.
           MOVE SRC-U5V2 TO E-DEC-FIX.
           MOVE E-DEC-FIX TO ACTUAL-RESULT.
           MOVE "012,30" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-003-GROUPING-PERIOD.

           MOVE "T003" TO TEST-ID.
           MOVE "PERIOD GROUP INSERTION PIC 9.999" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 1234 TO SRC-U4.
           MOVE SRC-U4 TO E-GROUP-FIX.
           MOVE E-GROUP-FIX TO ACTUAL-RESULT.
           MOVE "1.234" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-004-ZERO-SUPPRESSION.

           MOVE "T004" TO TEST-ID.
           MOVE "ZERO SUPPRESSION PIC ZZZ9" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 12 TO SRC-U4.
           MOVE SRC-U4 TO E-ZZZ9.
           MOVE E-ZZZ9 TO ACTUAL-RESULT.
           MOVE "  12" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-005-STAR-PROTECTION.

           MOVE "T005" TO TEST-ID.
           MOVE "CHECK PROTECTION PIC ***9" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 12 TO SRC-U4.
           MOVE SRC-U4 TO E-STAR9.
           MOVE E-STAR9 TO ACTUAL-RESULT.
           MOVE "**12" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-010-LEADING-PLUS-POS.

           MOVE "T010" TO TEST-ID.
           MOVE "LEADING PLUS POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-S4.
           MOVE SRC-S4 TO E-PLUS-LEAD.
           MOVE E-PLUS-LEAD TO ACTUAL-RESULT.
           MOVE "+0123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-011-LEADING-PLUS-NEG.

           MOVE "T011" TO TEST-ID.
           MOVE "LEADING PLUS NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-S4.
           MOVE SRC-S4 TO E-PLUS-LEAD.
           MOVE E-PLUS-LEAD TO ACTUAL-RESULT.
           MOVE "-0123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-012-TRAILING-PLUS-POS.

           MOVE "T012" TO TEST-ID.
           MOVE "TRAILING PLUS POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-S4.
           MOVE SRC-S4 TO E-PLUS-TRAIL.
           MOVE E-PLUS-TRAIL TO ACTUAL-RESULT.
           MOVE "0123+" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-013-TRAILING-PLUS-NEG.

           MOVE "T013" TO TEST-ID.
           MOVE "TRAILING PLUS NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-S4.
           MOVE SRC-S4 TO E-PLUS-TRAIL.
           MOVE E-PLUS-TRAIL TO ACTUAL-RESULT.
           MOVE "0123-" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-020-LEADING-MINUS-POS.

           MOVE "T020" TO TEST-ID.
           MOVE "LEADING MINUS POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-S4.
           MOVE SRC-S4 TO E-MINUS-LEAD.
           MOVE E-MINUS-LEAD TO ACTUAL-RESULT.
           MOVE " 0123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-021-LEADING-MINUS-NEG.

           MOVE "T021" TO TEST-ID.
           MOVE "LEADING MINUS NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-S4.
           MOVE SRC-S4 TO E-MINUS-LEAD.
           MOVE E-MINUS-LEAD TO ACTUAL-RESULT.
           MOVE "-0123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-022-TRAILING-MINUS-POS.

           MOVE "T022" TO TEST-ID.
           MOVE "TRAILING MINUS POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-S4.
           MOVE SRC-S4 TO E-MINUS-TRAIL.
           MOVE E-MINUS-TRAIL TO ACTUAL-RESULT.
           MOVE "0123 " TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-023-TRAILING-MINUS-NEG.

           MOVE "T023" TO TEST-ID.
           MOVE "TRAILING MINUS NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-S4.
           MOVE SRC-S4 TO E-MINUS-TRAIL.
           MOVE E-MINUS-TRAIL TO ACTUAL-RESULT.
           MOVE "0123-" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-030-CR-POS.

           MOVE "T030" TO TEST-ID.
           MOVE "CR POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-S4.
           MOVE SRC-S4 TO E-CR.
           MOVE E-CR TO ACTUAL-RESULT.
           MOVE "0123  " TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-031-CR-NEG.

           MOVE "T031" TO TEST-ID.
           MOVE "CR NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-S4.
           MOVE SRC-S4 TO E-CR.
           MOVE E-CR TO ACTUAL-RESULT.
           MOVE "0123CR" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-032-DB-POS.

           MOVE "T032" TO TEST-ID.
           MOVE "DB POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-S4.
           MOVE SRC-S4 TO E-DB.
           MOVE E-DB TO ACTUAL-RESULT.
           MOVE "0123  " TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-033-DB-NEG.

           MOVE "T033" TO TEST-ID.
           MOVE "DB NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-S4.
           MOVE SRC-S4 TO E-DB.
           MOVE E-DB TO ACTUAL-RESULT.
           MOVE "0123DB" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-040-CURRENCY-FIXED.

           MOVE "T040" TO TEST-ID.
           MOVE "FIXED CURRENCY" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-U4.
           MOVE SRC-U4 TO E-CURRENCY-FIX.
           MOVE E-CURRENCY-FIX TO ACTUAL-RESULT.
           MOVE "$0123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-041-CURRENCY-FLOAT.

           MOVE "T041" TO TEST-ID.
           MOVE "FLOATING CURRENCY" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-U5.
           MOVE SRC-U5 TO E-CURRENCY-FLOAT.
           MOVE E-CURRENCY-FLOAT TO ACTUAL-RESULT.
           MOVE " $123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-042-FLOATING-PLUS-POS.

           MOVE "T042" TO TEST-ID.
           MOVE "FLOATING PLUS POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-S5.
           MOVE SRC-S5 TO E-PLUS-FLOAT.
           MOVE E-PLUS-FLOAT TO ACTUAL-RESULT.
           MOVE " +123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-043-FLOATING-PLUS-NEG.

           MOVE "T043" TO TEST-ID.
           MOVE "FLOATING PLUS NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-S5.
           MOVE SRC-S5 TO E-PLUS-FLOAT.
           MOVE E-PLUS-FLOAT TO ACTUAL-RESULT.
           MOVE " -123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-044-FLOATING-MINUS-POS.

           MOVE "T044" TO TEST-ID.
           MOVE "FLOATING MINUS POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123 TO SRC-S5.
           MOVE SRC-S5 TO E-MINUS-FLOAT.
           MOVE E-MINUS-FLOAT TO ACTUAL-RESULT.
           MOVE "  123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-045-FLOATING-MINUS-NEG.

           MOVE "T045" TO TEST-ID.
           MOVE "FLOATING MINUS NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-S5.
           MOVE SRC-S5 TO E-MINUS-FLOAT.
           MOVE E-MINUS-FLOAT TO ACTUAL-RESULT.
           MOVE " -123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-050-BLANK-INSERTION.

           MOVE "T050" TO TEST-ID.
           MOVE "BLANK INSERTION" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 1234 TO SRC-U4.
           MOVE SRC-U4 TO E-BLANK-INSERT.
           MOVE E-BLANK-INSERT TO ACTUAL-RESULT.
           MOVE "12 34" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-051-ZERO-INSERTION.

           MOVE "T051" TO TEST-ID.
           MOVE "ZERO INSERTION" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 12 TO SRC-U4.
           MOVE SRC-U4 TO E-ZERO-INSERT.
           MOVE E-ZERO-INSERT TO ACTUAL-RESULT.
           MOVE "1200" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-052-SLASH-INSERTION.

           MOVE "T052" TO TEST-ID.
           MOVE "SLASH INSERTION" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 12312026 TO SRC-U8.
           MOVE SRC-U8 TO E-SLASH-INSERT.
           MOVE E-SLASH-INSERT TO ACTUAL-RESULT.
           MOVE "12/31/2026" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-060-COMP-SOURCE.

           MOVE "T060" TO TEST-ID.
           MOVE "COMP INTEGER SOURCE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 789 TO SRC-COMP.
           MOVE SRC-COMP TO E-9999.
           MOVE E-9999 TO ACTUAL-RESULT.
           MOVE "0789" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-061-COMP-DECIMAL-SOURCE.

           MOVE "T061" TO TEST-ID.
           MOVE "COMP DECIMAL SOURCE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123,45 TO SRC-COMP-DEC.
           MOVE SRC-COMP-DEC TO E-DEC-FIX.
           MOVE E-DEC-FIX TO ACTUAL-RESULT.
           MOVE "123,45" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-062-COMP-1-SOURCE.

           MOVE "T062" TO TEST-ID.
           MOVE "COMP-1 FLOAT SOURCE INTEGER VALUE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 1234 TO SRC-COMP-1.
           MOVE SRC-COMP-1 TO E-9999.
           MOVE E-9999 TO ACTUAL-RESULT.
           MOVE "1234" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-063-COMP-2-SOURCE.

           MOVE "T063" TO TEST-ID.
           MOVE "COMP-2 FLOAT SOURCE NEGATIVE VALUE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -1234 TO SRC-COMP-2.
           MOVE SRC-COMP-2 TO E-PLUS-LEAD.
           MOVE E-PLUS-LEAD TO ACTUAL-RESULT.
           MOVE "-1234" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-064-COMP-3-SOURCE.

           MOVE "T064" TO TEST-ID.
           MOVE "COMP-3 PACKED DECIMAL SOURCE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 123,45 TO SRC-COMP-3.
           MOVE SRC-COMP-3 TO E-DEC-FIX.
           MOVE E-DEC-FIX TO ACTUAL-RESULT.
           MOVE "123,45" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-065-COMP-4-SOURCE.

           MOVE "T065" TO TEST-ID.
           MOVE "COMP-4 BINARY SOURCE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 4321 TO SRC-COMP-4.
           MOVE SRC-COMP-4 TO E-GROUP-FIX.
           MOVE E-GROUP-FIX TO ACTUAL-RESULT.
           MOVE "4.321" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-070-LEADING-SEPARATE-SOURCE.

           MOVE "T070" TO TEST-ID.
           MOVE "SIGNED LEADING SEPARATE SOURCE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-LEAD-SEP.
           MOVE SRC-LEAD-SEP TO E-PLUS-LEAD.
           MOVE E-PLUS-LEAD TO ACTUAL-RESULT.
           MOVE "-0123" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-071-TRAILING-SEPARATE-SOURCE.

           MOVE "T071" TO TEST-ID.
           MOVE "SIGNED TRAILING SEPARATE SOURCE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -123 TO SRC-TRAIL-SEP.
           MOVE SRC-TRAIL-SEP TO E-PLUS-TRAIL.
           MOVE E-PLUS-TRAIL TO ACTUAL-RESULT.
           MOVE "0123-" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-072-ARITHMETIC-SOURCE.

           MOVE "T072" TO TEST-ID.
           MOVE "ARITHMETIC RESULT SOURCE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           COMPUTE SRC-ARITH = 1000,25 + 234,25.
           MOVE SRC-ARITH TO E-COMPLEX-SIGN.
           MOVE E-COMPLEX-SIGN TO ACTUAL-RESULT.
           MOVE "$ 1.234,50 " TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-080-COMPLEX-POSITIVE.

           MOVE "T080" TO TEST-ID.
           MOVE "COMPLEX SIGN POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 1234,50 TO SRC-S5V2.
           MOVE SRC-S5V2 TO E-COMPLEX-SIGN.
           MOVE E-COMPLEX-SIGN TO ACTUAL-RESULT.
           MOVE "$ 1.234,50 " TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-081-COMPLEX-NEGATIVE.

           MOVE "T081" TO TEST-ID.
           MOVE "COMPLEX SIGN NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -1234,50 TO SRC-S5V2.
           MOVE SRC-S5V2 TO E-COMPLEX-SIGN.
           MOVE E-COMPLEX-SIGN TO ACTUAL-RESULT.
           MOVE "$ 1.234,50-" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-082-COMPLEX-CR-POSITIVE.

           MOVE "T082" TO TEST-ID.
           MOVE "COMPLEX CR POSITIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 1234,50 TO SRC-S5V2.
           MOVE SRC-S5V2 TO E-COMPLEX-CR.
           MOVE E-COMPLEX-CR TO ACTUAL-RESULT.
           MOVE "$ 1.234,50  " TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-083-COMPLEX-CR-NEGATIVE.

           MOVE "T083" TO TEST-ID.
           MOVE "COMPLEX CR NEGATIVE" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE -1234,50 TO SRC-S5V2.
           MOVE SRC-S5V2 TO E-COMPLEX-CR.
           MOVE E-COMPLEX-CR TO ACTUAL-RESULT.
           MOVE "$ 1.234,50CR" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-084-BLANK-WHEN-ZERO.

           MOVE "T084" TO TEST-ID.
           MOVE "BLANK WHEN ZERO WITH ZERO" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE ZERO TO SRC-U5V2.
           MOVE SRC-U5V2 TO E-BLANK-WHEN-ZERO.
           MOVE E-BLANK-WHEN-ZERO TO ACTUAL-RESULT.
           MOVE "      " TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.

       TEST-085-BLANK-WHEN-NONZERO.

           MOVE "T085" TO TEST-ID.
           MOVE "BLANK WHEN ZERO WITH NONZERO" TO TEST-NAME.
           MOVE SPACES TO ACTUAL-RESULT EXPECTED-RESULT.

           MOVE 12,30 TO SRC-U5V2.
           MOVE SRC-U5V2 TO E-BLANK-WHEN-ZERO.
           MOVE E-BLANK-WHEN-ZERO TO ACTUAL-RESULT.
           MOVE " 12,30" TO EXPECTED-RESULT.

           PERFORM ASSERT-RESULT.
